services:
  reverseproxy:
    image: nginxproxy
    ports:
      - 8888:5000
    restart: always
    depends_on:
      - server1
      - server2
  server1:
    image: nodeserver
    ports:
      - 3000:3000
    restart: always
  server2:
    image: nodeserver
    ports:
      - 3001:3000
    restart: always
