apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetoyproject
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetoyproject
  template:
    metadata:
      labels:
        app: kubetoyproject
    spec:
      containers:
        - name: server1
          image: vineethbuddha/nodeserver
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server1
  namespace: default
spec:
  type: NodePort
  selector:
    app: kubetoyproject
  ports:
    - port: 3000
      targetPort: 3000
